site_name: Python Introduction

nav:
  - Start: index.md
  - Morning Session:
    - Overview: morning_session/overview.md
    - Using The Python interpreter: morning_session/using_the_python_interpreter.md
    - The Way Of The Program: morning_session/the_way_of_the_program.md
    - Working with Python scripts: morning_session/working_with_python_scripts.md
    - Variables, expressions and statements: morning_session/variables_expressions_and_statements.md
#    - Lecture: morning_session/lecture.md
#    - Exercise: morning_session/exercise.md
  - Afternoon Session:
    - Overview: afternoon_session/overview.md
    - UPPMAX modules and Python packages: afternoon_session/hello_little_turtles.md
    - File IO: afternoon_session/files.md
    - Command-line arguments: afternoon_session/command_line_arguments.md
    - Graphics: afternoon_session/graphics.md
    - Functions: afternoon_session/functions.md
#    - Lecture: afternoon_session/lecture.md
#    - Exercise: afternoon_session/exercise.md

theme:
  name: material
  greetings: Welcome to UPPMAX userguide
  font:
    # text: Lato
    code: JetBrains Mono


  logo: assets/logo.svg

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate
    - content.tabs.link

  custom_dir: mkdocs_uppmax/
    
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
